insert into produtos_nome (nome) values
('Detergente'),
('Sabonete'),
('Biscoito'),
('Macarrão'),
('Farinha de Trigo'),
('Farinha de mandioca'),
('Refresco em pó'),
('Arroz tipo 1'),
('Feijão carioca'),
('Feijão preto'),
('Sabão em Pó'),
('Sabão em barra'),
('Esponja'),
('Leite Integral'),
('Leite desnatado'),
('Leite semi-desnatado'),
('Refrigerante Limão'),
('Refrigerante Uva'),
('Refrigerante Cola'),
('Refrigerante laranja'),
('Refrigerante'),
('Cerveja'),
('Papel higiênico'),
('Papel toalha'),
('Antitranspirante'),
('Desodorante'),
('Leite condensado'),
('Creme de leite'),
('Leite de coco'),
('Café em pó'),
('Café-solúvel'),
('Açucar Refinado'),
('Açucar mascavo'),
('Adoçante');