/*
 * Copyright 2019 Optimus.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package br.osasco.optimus.omarket;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author brasilio
 */
public class MainFrame extends javax.swing.JFrame {
    private final File cnf_file = new File(System.getProperty("user.home") + "/market.properties");
    private Connection dbh = null;
    private Properties cnf = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        try {
            cnf = loadConfigs();
            dbh = dbConnect();
        }
        catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex, "Erro ao carregar a aplicação", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
    
    private Connection dbConnect() throws SQLException {
        if (cnf == null) {
            return null;
        }
        String url = String.format("jdbc:%s://%s:%s/%s", cnf.getProperty("db.type"), cnf.getProperty("db.host"), cnf.getProperty("db.port"), cnf.getProperty("db.name"));
        return DriverManager.getConnection(url, cnf.getProperty("db.user"), cnf.getProperty("db.pass"));
    }
    
    private Properties loadConfigs() throws IOException {
        cnf = new Properties();
        if (!cnf_file.exists()) {
            cnf.setProperty("db.host", "localhost");
            cnf.setProperty("db.user", "omarket");
            cnf.setProperty("db.pass", "");
            cnf.setProperty("db.name", "optimus_market");
            cnf.setProperty("db.port", "5432");
            cnf.setProperty("db.type", "postgresql");
            try (OutputStream stream = new FileOutputStream(cnf_file)) {
                cnf.store(stream, "Arquivo gerado.");
            }
            return cnf;
        }
        try (InputStream stream = new FileInputStream(cnf_file)) {
            cnf.load(stream);
        }
        return cnf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopMain = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuUsers = new javax.swing.JMenu();
        acUserReg = new javax.swing.JMenuItem();
        acUserList = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFile.setText("Arquivo");
        menuBar.add(menuFile);

        menuUsers.setText("Usuários");

        acUserReg.setText("Registrar");
        acUserReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acUserRegActionPerformed(evt);
            }
        });
        menuUsers.add(acUserReg);

        acUserList.setText("Lista de usuários");
        acUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acUserListActionPerformed(evt);
            }
        });
        menuUsers.add(acUserList);

        menuBar.add(menuUsers);

        menuProdutos.setText("Produtos");
        menuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProdutos.add(jMenuItem1);

        menuBar.add(menuProdutos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopMain, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acUserRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acUserRegActionPerformed
        br.osasco.optimus.omarket.usuario.FrameRegister fm = new br.osasco.optimus.omarket.usuario.FrameRegister(dbh);
        desktopMain.add(fm);
        fm.setVisible(true);
    }//GEN-LAST:event_acUserRegActionPerformed

    private void acUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acUserListActionPerformed
        br.osasco.optimus.omarket.usuario.FrameOpen fm = new br.osasco.optimus.omarket.usuario.FrameOpen(dbh);
        desktopMain.add(fm);
        fm.setVisible(true);
    }//GEN-LAST:event_acUserListActionPerformed

    private void menuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProdutosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        br.osasco.optimus.omarket.produto.FrameRegister fm = new br.osasco.optimus.omarket.produto.FrameRegister(dbh);
        desktopMain.add(fm);
        fm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acUserList;
    private javax.swing.JMenuItem acUserReg;
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuUsers;
    // End of variables declaration//GEN-END:variables
}
